# Generated by Django 2.1.5 on 2019-02-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('house', 'course_name', 'year')},
        ),
    ]
