# Generated by Django 2.1.5 on 2019-02-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortinghat', '0002_auto_20190204_0237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='house',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AlterUniqueTogether(
            name='courserank',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courserank',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courserank',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='courserank',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='houserank',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='houserank',
            name='house',
        ),
        migrations.RemoveField(
            model_name='houserank',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='houserank',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='course',
        ),
        migrations.RemoveField(
            model_name='match',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='match',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseRank',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='HouseRank',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
