# Generated by Django 2.1.5 on 2019-02-04 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sortinghat', '0003_auto_20190204_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Course')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.Semester')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.House')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.Semester')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Course')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.Semester')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='houserank',
            unique_together={('student', 'rank', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courserank',
            unique_together={('student', 'rank', 'semester')},
        ),
    ]
